### ISSUE TITLE
[Bug]: Crash with mod shoulder surfing reloaded mod 1.19

### ISSUE THREAD

**Issue by Alastor8881** [Fuzss/forgeconfigapiport-fabric#14]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19

### Mod Version (Required)

4.0.2

### Notes (Required)

Hello i found a bug with the version 4.0.2 1.19 minceraft fabric, it just crahes not fully sure why it does it. under here is the log and yes i do have forge config api in my mods folder idk why it says on the log i dont have forge config api.

[20:22:07] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.9
[20:22:10] [ForkJoinPool-1-worker-4/WARN]: Mod weaponmaster uses the version 3.0.0  which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0 '!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[20:22:15] [main/WARN]: Mod resolution failed
[20:22:15] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE shouldersurfing 2.2.9 {depends forgeconfigapiport @ [>=4.0.0]}, ROOT_FORCELOAD_SINGLE shouldersurfing 2.2.9]
[20:22:15] [main/INFO]: Reason: [HARD_DEP shouldersurfing 2.2.9 {depends forgeconfigapiport @ [>=4.0.0]}]
[20:22:15] [main/INFO]: Fix: add [add:forgeconfigapiport 4.0.0 ([[4.0.0,?)])], remove [], replace []
[20:22:15] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install forgeconfigapiport, version 4.0.0 or later.
Unmet dependency listing:
	 - Mod 'Shoulder Surfing Reloaded' (shouldersurfing) 2.2.9 requires version 4.0.0 or later of forgeconfigapiport, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

**Comment by Alastor8881** [comment]
nvm think i found the problem
